gazebo_ros_control:
  pid_gains:
    front_left_wheel_motor_joint:
      p: 0.0
      i: 0.0
      d: 0.0
    front_right_wheel_motor_joint:
      p: 0.0
      i: 0.0
      d: 0.0
    rear_left_wheel_motor_joint:
      p: 0.0
      i: 0.0
      d: 0.0
    rear_right_wheel_motor_joint:
      p: 0.0
      i: 0.0
      d: 0.0
