joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: head_link_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}