obstacle_range: 1.75
raytrace_range: 5.0
footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.15]]
robot_radius: 0.30
inflation_radius: 0.32
transform_tolerance: 2.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}